title = "Cursor"  # From Git
gitRepoUrl = "https://github.com/Data-Oriented-House/Cursor" # From Git

gitSourceBranch = "main"
changelog = false

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Performant"
description = "Carefully optimized speed and api design for encoding numbers, booleans, strings, and variable-length-quantities into buffers."

[[home.features]]
title = "Dynamic Stack"
description = "Push and pop data of various formats off buffers turned into dynamically sized stacks to quickly encode data into buffers."
image = "/Cursor.png"

[[home.features]]
title = "Ergonomic"
description = "A dead-simple, flat procedural and object api to let you focus on encoding your data."

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "Data-Oriented-House"
projectName = "Squash"
url = "https://data-oriented-house.github.io"
baseUrl = "/Cursor/"
tagline = "Luau's Dynamic Bytestack"

[navbar.logo]
src = "/favicon.ico"

[footer]
style = "dark"
copyright = "Copyright © 2024 SolarScuffle-Bot. Built with Moonwave and Docusaurus"